### ISSUE TITLE
Add golangci-lint to the build step

### ISSUE THREAD

**Issue by shanev** [public-awesome/stakebird#109]
Either use the image at https://hub.docker.com/r/golangci/golangci-lint, or download it and run `make lint`.

Maybe not related to the issue but adding golangci-lint to the build step could be nice as well

_Originally posted by @jhernandezb in https://github.com/public-awesome/stakebird/issues/107#issuecomment-657275624_

**Comment by JakeHartnell** [comment]
Note, there are a lot of errors to fix. :joy:
