### ISSUE TITLE
Add ledger support

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/stakebird#267]
Tried to add a key on ledger to see if it worked for fun. Got:
```
Error: ledger nano S: support for ledger devices is not available in this executable
```

I think we just need to enable a build flag or something simple like that. https://github.com/cosmos/cosmos-sdk/issues/5272

Would be nice to support some hardware wallets if it's relatively straight forward.

**Comment by jhernandezb** [comment]
Its already in our makefile, did you tried `LEDGER_ENABLED=true make install`?

**Comment by JakeHartnell** [comment]
Ahhhhhhhhhhh, silly me. Closing.
