### ISSUE TITLE
STARS / CREDITS AMM

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/stakebird#278]
As a user, I would like to be able to purchase more CREDITS with STARS tokens if I run out or use more than my daily allotment of CREDITS. I should be able to purchase more CREDITS with STARS tokens.

Unlike my daily allocation of CREDITS, credits I purchase should NOT expire. See: https://github.com/public-awesome/stakebot/issues/266

We should setup some sort of Automated Market Maker for exchanging STARS for CREDITS.

Swapping CREDITS for STARS should incur a 5% fee to the community pool, see: https://discord.com/channels/755548171941445642/755564065794818089/800469061183602689

**Comment by shanev** [comment]
Cosmos Liquidity module https://github.com/tendermint/liquidity
