### ISSUE TITLE
Figure out how to handle the result of governance moderation

### ISSUE THREAD

**Issue by shanev** [public-awesome/stakebird#51]
Options:
* Fork the Cosmos Governance module, adding a new proposal type for content moderation. Add events to signal the result of governance votes, so rewards can be paid out (or slashed). Furthermore, the post and upvotes have to be either deleted or flagged, or curation has to resume, accounting for the moderation delay.
* See if just a text proposal is enough, but if its possible to hook into the results to do the redistribution.

**Comment by JakeHartnell** [comment]
> Fork the Cosmos Governance module, adding a new proposal type for content moderation. Add events to signal the result of governance votes, so rewards can be paid out (or slashed). Furthermore, the post and upvotes have to be either deleted or flagged, or curation has to resume, accounting for the moderation delay.

+1, I think it makes sense to fork it.

**Comment by shanev** [comment]
Closing until there's a data layer.
