### ISSUE TITLE
Appeal process

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/stakebird#71]
[The Santa Clara Principles on Transparency and Accountability in Content Moderation](https://santaclaraprinciples.org/) have a core principle of appeal:
> Companies should provide a meaningful opportunity for timely appeal of any content removal or account suspension.

While I feel we are doing well with regard to the other principles, an appeal process is something that is definitely worth looking into supporting on chain.

**Comment by shanev** [comment]
Closing until there's a data layer
